# fly.toml app configuration file generated for splitaddress on 2023-05-27T15:15:29+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "splitaddress"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
